apiVersion: v1
kind: Secret
metadata:
  name: commerce-secrets
  namespace: commerce
  labels:
    app.kubernetes.io/name: commerce-platform
    app.kubernetes.io/part-of: ecommerce-microservices
type: Opaque
stringData:
  JWT_SECRET: "commerce-super-secret-production-jwt-key-change-in-vault"
  STRIPE_SECRET_KEY: "placeholder_test_key_not_real"
  STRIPE_WEBHOOK_SECRET: "whsec_placeholder_for_kubernetes_deployment"
  RABBITMQ_DEFAULT_PASS: "guest"
  DATABASE_URL_USERS: "postgresql://postgres:${DB_PASSWORD}@users-db:5432/users"
  DATABASE_URL_CATALOG: "postgresql://postgres:${DB_PASSWORD}@catalog-db:5432/catalog"
  DATABASE_URL_ORDERS: "postgresql://postgres:${DB_PASSWORD}@orders-db:5432/orders"
  DATABASE_URL_PAYMENTS: "postgresql://postgres:${DB_PASSWORD}@payments-db:5432/payments"
  DATABASE_URL_INVENTORY: "postgresql://postgres:${DB_PASSWORD}@inventory-db:5432/inventory"
  DATABASE_URL_SHIPPING: "postgresql://postgres:${DB_PASSWORD}@shipping-db:5432/shipping"
  DATABASE_URL_REVIEWS: "postgresql://postgres:${DB_PASSWORD}@reviews-db:5432/reviews"
  DATABASE_URL_PRICING: "postgresql://postgres:${DB_PASSWORD}@pricing-db:5432/pricing"
