import { MigrationInterface, QueryRunner, Table, TableIndex } from 'typeorm';

/**
 * M10: the shipment — the first thing in this project that outlives the request
 * that created it.
 *
 * Every other aggregate here reaches a terminal state in minutes: an order
 * confirms or cancels, a reservation commits or expires, a coupon use is spent
 * or given back. A shipment is created when an order confirms and then sits in
 * `pending` for a day and `dispatched` for a week, reaching `delivered` because
 * a human said so — long after every saga involved has finished.
 *
 * ## `order_id` UNIQUE is the point of this table
 *
 * It is what makes creating a shipment idempotent. The bus delivers at least
 * once, so `order.confirmed` will arrive twice for some order eventually, and
 * two parcels is a real cost rather than a tidy-up. Two independent guards stop
 * it, exactly as M9 established:
 *
 *   1. `processed_events` — a redelivered event id is a no-op.
 *   2. this index — a **republished** event with a *new* id, which the marker
 *      cannot catch, violates it instead.
 *
 * M9 proved guard 1 alone is insufficient by testing precisely that case.
 *
 * ## Three states, not four
 *
 * docs/M10_SHIPPING_PLAN.md §8 sketched a `cancelled` state. Nothing reaches
 * it: shipments are created from `order.confirmed`, so a cancelled order never
 * has one, and there is no return or post-delivery refund flow until R4. It is
 * left out rather than carried as a value nothing writes — the same test this
 * project applied to `order.created`'s payload and to pricing's outbox.
 */
export class CreateShipments1735004600000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TYPE "shipment_status_enum" AS ENUM ('pending', 'dispatched', 'delivered')`,
    );

    await queryRunner.createTable(
      new Table({
        name: 'shipments',
        columns: [
          {
            name: 'id',
            type: 'uuid',
            isPrimary: true,
            isGenerated: true,
            generationStrategy: 'uuid',
          },
          // Uniqueness comes from the named index below, not `isUnique` here —
          // setting both creates two indexes enforcing one rule, and the error
          // then names an autogenerated constraint nobody can find in the
          // codebase. Same note as M9's coupon_redemptions.
          { name: 'order_id', type: 'uuid' },
          { name: 'customer_id', type: 'uuid' },
          { name: 'status', type: 'shipment_status_enum', default: `'pending'` },
          // All three frozen: what was chosen, what it cost, what it was rated
          // on. A rate table edited next month must not change this parcel.
          { name: 'rate_code', type: 'varchar', isNullable: true },
          { name: 'cost_minor', type: 'integer', default: 0 },
          { name: 'weight_g', type: 'integer', default: 0 },
          { name: 'address', type: 'jsonb', isNullable: true },
          { name: 'carrier', type: 'varchar', isNullable: true },
          { name: 'tracking_code', type: 'varchar', isNullable: true },
          { name: 'dispatched_at', type: 'timestamptz', isNullable: true },
          { name: 'delivered_at', type: 'timestamptz', isNullable: true },
          { name: 'created_at', type: 'timestamptz', default: 'now()' },
          { name: 'updated_at', type: 'timestamptz', default: 'now()' },
        ],
        checks: [
          { name: 'CHK_shipments_cost_non_negative', expression: '"cost_minor" >= 0' },
          { name: 'CHK_shipments_weight_non_negative', expression: '"weight_g" >= 0' },
          /**
           * The timestamps must agree with the status they describe.
           *
           * A `delivered` row with no `delivered_at`, or a `pending` row that
           * somehow has one, is a state machine that has been driven by an
           * UPDATE rather than by the service — and it would read as a
           * perfectly ordinary row. This makes that loud.
           */
          {
            name: 'CHK_shipments_timestamps_match_status',
            expression:
              `("status" = 'pending'    AND "dispatched_at" IS NULL AND "delivered_at" IS NULL) OR ` +
              `("status" = 'dispatched' AND "dispatched_at" IS NOT NULL AND "delivered_at" IS NULL) OR ` +
              `("status" = 'delivered'  AND "dispatched_at" IS NOT NULL AND "delivered_at" IS NOT NULL)`,
          },
        ],
      }),
    );

    // One shipment per order, ever. See the class note.
    await queryRunner.createIndex(
      'shipments',
      new TableIndex({
        name: 'UQ_shipments_order',
        columnNames: ['order_id'],
        isUnique: true,
      }),
    );

    // "My deliveries", newest first.
    await queryRunner.createIndex(
      'shipments',
      new TableIndex({
        name: 'IDX_shipments_customer',
        columnNames: ['customer_id', 'created_at'],
      }),
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropIndex('shipments', 'IDX_shipments_customer');
    await queryRunner.dropIndex('shipments', 'UQ_shipments_order');
    await queryRunner.dropTable('shipments');
    await queryRunner.query(`DROP TYPE "shipment_status_enum"`);
  }
}
