apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        filterByTraceId: true
        filterBySpanId: true
        customQuery: true
        query: '{job="docker"} |= "$${__trace.id}"'
      lokiSearch:
        datasourceUid: 'loki'

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    isDefault: true
    editable: false
    jsonData:
      maxLines: 2000
      derivedFields:
        - datasourceUid: 'Tempo'
          matcherRegex: '(?:"traceId"|"trace_id"|traceId=)"?([0-9a-fA-F]{32})'
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: 'View in Tempo'
