apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: commerce-production

resources:
  - ../../base

namePrefix: prod-

labels:
  - pairs:
      environment: production

patches:
  - target:
      kind: Ingress
      name: commerce-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: shop.example.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: shop.example.com
  - target:
      kind: ConfigMap
      name: commerce-config
    patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: "warn"
      - op: replace
        path: /data/NODE_ENV
        value: "production"
  - target:
      kind: Deployment
      name: (api-gateway|orders-service|storefront)
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
