/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current cart (guest or signed in) */
        get: operations["CartController_get"];
        put?: never;
        post?: never;
        /** Empty the cart */
        delete: operations["CartController_clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a product, accumulating onto any existing line */
        post: operations["CartController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cart/items/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a line */
        delete: operations["CartController_remove"];
        options?: never;
        head?: never;
        /** Set an absolute quantity; zero removes the line */
        patch: operations["CartController_setQty"];
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddCartItemDto: {
            productId: string;
            /** @example 1 */
            qty: number;
        };
        CartLineDto: {
            productId: string;
            qty: number;
        };
        CartResponseDto: {
            /** @description A new guest cart token to store, or null once the guest cart has been merged and the client should forget it. */
            cartToken?: Record<string, never> | null;
            items: components["schemas"]["CartLineDto"][];
            /** @description Present only on the response that merged a guest cart in, so the UI can explain what changed. */
            merged?: components["schemas"]["MergeSummaryDto"];
        };
        MergeAdjustmentDto: {
            /** @description Zero means the line was dropped. */
            finalQty: number;
            productId: string;
            /** @enum {string} */
            reason: "capped_to_stock" | "out_of_stock" | "unavailable";
            requestedQty: number;
        };
        MergeSummaryDto: {
            adjustments: components["schemas"]["MergeAdjustmentDto"][];
        };
        SetCartItemQtyDto: {
            /**
             * @description Zero removes the line.
             * @example 2
             */
            qty: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    CartController_get: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-cart-token": string;
                "x-correlation-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponseDto"];
                };
            };
        };
    };
    CartController_clear: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-cart-token": string;
                "x-correlation-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponseDto"];
                };
            };
        };
    };
    CartController_add: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-cart-token": string;
                "x-correlation-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCartItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponseDto"];
                };
            };
        };
    };
    CartController_remove: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-cart-token": string;
                "x-correlation-id": string;
            };
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponseDto"];
                };
            };
        };
    };
    CartController_setQty: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-cart-token": string;
                "x-correlation-id": string;
            };
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCartItemQtyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartResponseDto"];
                };
            };
        };
    };
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
