/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my orders */
        get: operations["OrdersController_list"];
        put?: never;
        /** Place an order */
        post: operations["OrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of my orders */
        get: operations["OrdersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateOrderDto: {
            /** @example SAVE10USES */
            couponCode?: string;
            destination?: components["schemas"]["OrderDestinationDto"];
            items: components["schemas"]["OrderLineDto"][];
            /** @description One of the caller's saved address ids. */
            shippingAddressId?: string;
            /** @example standard */
            shippingRateCode?: string;
        };
        OrderAddressResponseDto: {
            city: string;
            country: string;
            line1: string;
            line2?: Record<string, never> | null;
            phone?: Record<string, never> | null;
            postcode?: Record<string, never> | null;
            recipient: string;
            region?: Record<string, never> | null;
        };
        OrderDestinationDto: {
            /**
             * @description ISO 3166-1 alpha-2.
             * @example US
             */
            country: string;
            /**
             * @description State or province code.
             * @example CA
             */
            region?: string;
        };
        OrderItemResponseDto: {
            id: string;
            /** @description This line’s share of every discount that applied. */
            lineDiscountMinor: number;
            name: string;
            productId: string;
            qty: number;
            sku: string;
            /** @description This line’s share of its tax group’s single rounded figure. */
            taxMinor: number;
            /** @description Basis points: 725 is 7.25%. */
            taxRateBp: number;
            /** @description Integer minor units. */
            unitPriceMinor: number;
        };
        OrderLineDto: {
            productId: string;
            /** @example 2 */
            qty: number;
        };
        OrderResponseDto: {
            /** Format: date-time */
            createdAt: string;
            currency: string;
            customerId: string;
            /** @description What promotions took off, summed. */
            discountMinor: number;
            failureReason?: Record<string, never> | null;
            id: string;
            items: components["schemas"]["OrderItemResponseDto"][];
            /** @description Where it is going, frozen at checkout. Null when no address was given. */
            shippingAddress?: components["schemas"]["OrderAddressResponseDto"] | null;
            /** @description What delivery cost. Zero before M10, and zero when free. */
            shippingMinor: number;
            /** @description Which service level was charged. Null for orders placed before M10. */
            shippingRateCode?: Record<string, never> | null;
            /** @enum {string} */
            status: "pending" | "awaiting_payment" | "confirmed" | "cancelled" | "failed";
            /** @description The basket before anything was applied. */
            subtotalMinor: number;
            /** @description Null for orders placed before M8. */
            taxCountry?: Record<string, never> | null;
            /** @description Integer minor units. */
            taxMinor: number;
            taxRegion?: Record<string, never> | null;
            /** @description What the customer pays. Includes tax from M8, shipping from M10. */
            totalMinor: number;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_list: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"][];
                };
            };
        };
    };
    OrdersController_create: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-correlation-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
        };
    };
    OrdersController_findOne: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
        };
    };
    AppController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
