/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/coupons/hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim one use of a coupon for an order */
        post: operations["CouponsController_hold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/coupons/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release a held coupon use for an order that was never created */
        post: operations["CouponsController_release"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/coupons/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate a coupon code without redeeming it */
        get: operations["CouponsController_validate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/discounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Promotions currently active */
        get: operations["PricingController_discounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Price a basket: subtotal, discounts, tax, total */
        post: operations["PricingController_quote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/tax-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every tax rule, most general first */
        get: operations["PricingController_taxRates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppliedDiscountResponseDto: {
            /** @description Integer minor units. */
            amountMinor: number;
            id: string;
            name: string;
        };
        CreateQuoteDto: {
            /** @example SAVE10USES */
            couponCode?: string;
            customerId?: string;
            destination?: components["schemas"]["DestinationDto"];
            items: components["schemas"]["QuoteLineDto"][];
        };
        DestinationDto: {
            /**
             * @description ISO 3166-1 alpha-2.
             * @example US
             */
            country: string;
            /**
             * @description State or province code.
             * @example CA
             */
            region?: string;
        };
        HoldCouponDto: {
            /** @description What the coupon took off, in integer minor units. */
            amountMinor: number;
            /** @example SAVE10USES */
            code: string;
            customerId: string;
            orderId: string;
        };
        QuoteCouponResponseDto: {
            /** @description Integer minor units. */
            amountMinor: number;
            /** @description Whether it actually came off this basket. */
            applied: boolean;
            code: string;
            /** @description Why it did not apply: expired, exhausted, per_customer_limit, and so on. */
            rejectedBecause?: Record<string, never> | null;
        };
        QuoteLineDto: {
            productId: string;
            /** @example 2 */
            qty: number;
        };
        QuoteLineResponseDto: {
            /** @description This line’s share of every discount that applied. */
            lineDiscountMinor: number;
            /** @description Integer minor units. */
            lineSubtotalMinor: number;
            name: string;
            productId: string;
            qty: number;
            sku: string;
            /** @description This line’s share of its tax group’s single rounded figure. */
            taxMinor: number;
            /** @description Basis points: 725 is 7.25%. */
            taxRateBp: number;
            /** @description Subtotal less discount — what tax is charged on. */
            taxableMinor: number;
            /** @description Integer minor units. */
            unitPriceMinor: number;
        };
        QuoteResponseDto: {
            appliedDiscounts: components["schemas"]["AppliedDiscountResponseDto"][];
            coupon?: components["schemas"]["QuoteCouponResponseDto"] | null;
            currency: string;
            destination: components["schemas"]["DestinationDto"];
            discountMinor: number;
            lines: components["schemas"]["QuoteLineResponseDto"][];
            /** @description The amount excluding tax. */
            netMinor: number;
            /** @description Before any discount or tax. */
            subtotalMinor: number;
            /** @description One entry per tax rate in the basket. Tax is rounded once per group, and this is that rounding made visible. */
            taxBreakdown: components["schemas"]["TaxGroupResponseDto"][];
            taxMinor: number;
            /** @description What the customer pays. */
            totalMinor: number;
        };
        TaxGroupResponseDto: {
            /** @description Sum of the group’s taxable amounts, exact. */
            baseMinor: number;
            /** @description Whether the price already contained this tax. */
            pricesIncludeTax: boolean;
            /** @description Basis points: 725 is 7.25%. */
            rateBp: number;
            /** @description Rounded exactly once, for the whole group. */
            taxMinor: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CouponsController_hold: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldCouponDto"];
            };
        };
        responses: {
            /** @description Whether the use was granted, and why not if it was refused. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CouponsController_release: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CouponsController_validate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PricingController_discounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PricingController_quote: {
        parameters: {
            query?: never;
            header: {
                "x-correlation-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuoteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponseDto"];
                };
            };
        };
    };
    PricingController_taxRates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
