/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get enriched co-purchase product recommendations
         * @description Returns products frequently bought together with the requested product.
         */
        get: operations["RecommendationsController_getRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RecommendationsResponseDto: {
            items: components["schemas"]["RecommendedProductDto"][];
            /**
             * @description Total enriched items returned.
             * @example 4
             */
            total: number;
        };
        RecommendedProductDto: {
            /**
             * @description Co-purchase count in confirmed orders.
             * @example 3
             */
            coPurchaseCount: number;
            /** @example USD */
            currency: string;
            /** @example Black T-Shirt (M) */
            name: string;
            /**
             * @description Integer minor units. 1999 = $19.99.
             * @example 1999
             */
            priceMinor: number;
            /** @description Catalog product UUID. */
            productId: string;
            /** @example TSH-BLK-M */
            sku: string;
            /** @example black-t-shirt-medium */
            slug: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RecommendationsController_getRecommendations: {
        parameters: {
            query?: {
                /** @description Maximum number of recommendation cards to return. */
                limit?: number;
            };
            header: {
                "x-correlation-id": string;
            };
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponseDto"];
                };
            };
        };
    };
}
