/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/admin/republish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-emit product.rating_changed for all ratings (staff replay) */
        post: operations["ModerationController_republish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my authored reviews */
        get: operations["ReviewsController_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/moderation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reviews in moderation queue (staff) */
        get: operations["ModerationController_listModeration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List approved reviews for a product (public, newest first) */
        get: operations["ReviewsController_listForProduct"];
        put?: never;
        /** Submit a review for a purchased product */
        post: operations["ReviewsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/products/{productId}/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check if current customer can review this product */
        get: operations["ReviewsController_eligibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit an existing review (owner only; resets status to pending) */
        patch: operations["ReviewsController_update"];
        trace?: never;
    };
    "/api/v1/reviews/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a review (staff) */
        post: operations["ModerationController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a review (staff) */
        post: operations["ModerationController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateReviewDto: {
            /** @example Comfortable material and true to size. */
            body: string;
            /**
             * @description Star rating 1–5 integer.
             * @example 5
             */
            rating: number;
            /** @example Great fit and feel */
            title: string;
        };
        EligibilityResponseDto: {
            /**
             * @description True if customer has confirmed purchases and no existing review for this product.
             * @example true
             */
            canReview: boolean;
            /**
             * @description Alias for existingReviewId.
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            existing?: Record<string, never> | null;
            /**
             * @description Existing review ID if customer already reviewed this product.
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            existingReviewId?: Record<string, never> | null;
            /** @example Eligible to review */
            reason: string;
        };
        ModerateDto: {
            /**
             * @description Optional internal moderation note.
             * @example Content adheres to community guidelines
             */
            moderationNote?: string;
        };
        PaginatedReviewsResponseDto: {
            items: components["schemas"]["PublicReviewDto"][];
            /** @example 10 */
            limit: number;
            /** @example 1 */
            page: number;
            /** @example 42 */
            total: number;
        };
        PublicReviewDto: {
            /** @example Alex M. */
            authorName: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            productId: string;
            /** @example 5 */
            rating: number;
            title: string;
        };
        ReviewResponseDto: {
            /** @example Alex Doe */
            authorName: string;
            /** @example Comfortable material and true to size. */
            body: string;
            /** Format: date-time */
            createdAt: string;
            /** @example c3d4e5f6-a7b8-9012-cdef-123456789012 */
            customerId: string;
            /** @example a1b2c3d4-e5f6-7890-abcd-ef1234567890 */
            id: string;
            moderatedAt?: Record<string, never> | null;
            moderationNote?: Record<string, never> | null;
            /** @example d4e5f6a7-b8c9-0123-def1-234567890123 */
            orderId: string;
            /** @example b2c3d4e5-f6a7-8901-bcde-f12345678901 */
            productId: string;
            /** @example 5 */
            rating: number;
            /**
             * @example approved
             * @enum {string}
             */
            status: "pending" | "approved" | "rejected";
            /** @example Great fit and feel */
            title: string;
            /** Format: date-time */
            updatedAt: string;
            /** @example 1 */
            version: number;
        };
        UpdateReviewDto: {
            /** @example Updated review content. */
            body?: string;
            /** @example 4 */
            rating?: number;
            /** @example Updated title */
            title?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ModerationController_republish: {
        parameters: {
            query?: never;
            header?: {
                /** @description Set by the gateway from the verified JWT. */
                "x-user-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewsController_listMine: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponseDto"][];
                };
            };
        };
    };
    ModerationController_listModeration: {
        parameters: {
            query?: {
                /** @description Filter reviews by moderation status. */
                status?: "pending" | "approved" | "rejected";
                page?: number;
                limit?: number;
            };
            header?: {
                /** @description Set by the gateway from the verified JWT. */
                "x-user-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedReviewsResponseDto"];
                };
            };
        };
    };
    ReviewsController_listForProduct: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: {
                /** @description Set by the gateway from the verified JWT. */
                "x-user-id"?: string;
            };
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedReviewsResponseDto"];
                };
            };
        };
    };
    ReviewsController_create: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
                "x-correlation-id": string;
            };
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponseDto"];
                };
            };
        };
    };
    ReviewsController_eligibility: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
            };
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityResponseDto"];
                };
            };
        };
    };
    ReviewsController_update: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponseDto"];
                };
            };
        };
    };
    ModerationController_approve: {
        parameters: {
            query?: never;
            header?: {
                /** @description Set by the gateway from the verified JWT. */
                "x-user-id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponseDto"];
                };
            };
        };
    };
    ModerationController_reject: {
        parameters: {
            query?: never;
            header?: {
                /** @description Set by the gateway from the verified JWT. */
                "x-user-id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerateDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponseDto"];
                };
            };
        };
    };
}
