/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Price delivery of a basket by weight and destination */
        post: operations["RatesController_rates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every shipping zone, highest priority first */
        get: operations["RatesController_zones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RateDestinationDto: {
            /**
             * @description ISO 3166-1 alpha-2.
             * @example US
             */
            country: string;
            /**
             * @description State or province code.
             * @example CA
             */
            region?: string;
        };
        RateOptionDto: {
            /** @example standard */
            code: string;
            /** @description What this costs for this basket. Zero when free applied. */
            costMinor: number;
            /** @example USD */
            currency: string;
            /** @description True when a free-shipping threshold zeroed a real price. */
            freeApplied: boolean;
            /** @description The band price before any threshold — for showing “was $5.99”. */
            listPriceMinor: number;
            /** @example Standard (3–5 days) */
            name: string;
        };
        RateRequestDto: {
            destination: components["schemas"]["RateDestinationDto"];
            /**
             * @description Discounted subtotal, integer minor units.
             * @example 4999
             */
            subtotalMinor: number;
            /**
             * @description Total basket weight in grams. Zero is valid.
             * @example 1200
             */
            weightGrams: number;
        };
        RateResponseDto: {
            /** @description What applies when the caller names no service level. Null when none do. */
            cheapestCode?: Record<string, never> | null;
            /** @description Cheapest first, ties by code. Empty when nothing ships to this destination. */
            options: components["schemas"]["RateOptionDto"][];
            weightGrams: number;
            /**
             * @description Null when no zone covers this destination — the shop does not ship there.
             * @example US-CA
             */
            zone?: Record<string, never> | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RatesController_rates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateResponseDto"];
                };
            };
        };
    };
    RatesController_zones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
