/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Price delivery of a basket by weight and destination */
        post: operations["RatesController_rates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/shipments/{id}/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a parcel delivered (staff) */
        post: operations["ShipmentsController_deliver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/shipments/{id}/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hand a parcel to the carrier (staff) */
        post: operations["ShipmentsController_dispatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/shipments/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The delivery for one of my orders */
        get: operations["ShipmentsController_findByOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipping/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every shipping zone, highest priority first */
        get: operations["RatesController_zones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DispatchShipmentDto: {
            /** @example DHL */
            carrier?: string;
            /** @example JD0002210123456789 */
            trackingCode?: string;
        };
        RateDestinationDto: {
            /**
             * @description ISO 3166-1 alpha-2.
             * @example US
             */
            country: string;
            /**
             * @description State or province code.
             * @example CA
             */
            region?: string;
        };
        RateOptionDto: {
            /** @example standard */
            code: string;
            /** @description What this costs for this basket. Zero when free applied. */
            costMinor: number;
            /** @example USD */
            currency: string;
            /** @description True when a free-shipping threshold zeroed a real price. */
            freeApplied: boolean;
            /** @description The band price before any threshold — for showing “was $5.99”. */
            listPriceMinor: number;
            /** @example Standard (3–5 days) */
            name: string;
        };
        RateRequestDto: {
            destination: components["schemas"]["RateDestinationDto"];
            /**
             * @description Discounted subtotal, integer minor units.
             * @example 4999
             */
            subtotalMinor: number;
            /**
             * @description Total basket weight in grams. Zero is valid.
             * @example 1200
             */
            weightGrams: number;
        };
        RateResponseDto: {
            /** @description What applies when the caller names no service level. Null when none do. */
            cheapestCode?: Record<string, never> | null;
            /** @description Cheapest first, ties by code. Empty when nothing ships to this destination. */
            options: components["schemas"]["RateOptionDto"][];
            weightGrams: number;
            /**
             * @description Null when no zone covers this destination — the shop does not ship there.
             * @example US-CA
             */
            zone?: Record<string, never> | null;
        };
        ShipmentAddressDto: {
            city: string;
            country: string;
            line1: string;
            line2?: Record<string, never> | null;
            phone?: Record<string, never> | null;
            postcode?: Record<string, never> | null;
            recipient: string;
            region?: Record<string, never> | null;
        };
        ShipmentResponseDto: {
            address?: components["schemas"]["ShipmentAddressDto"] | null;
            carrier?: Record<string, never> | null;
            /** @description What delivery cost. Zero when it was free. */
            costMinor: number;
            /** Format: date-time */
            createdAt: string;
            customerId: string;
            deliveredAt?: Record<string, never> | null;
            dispatchedAt?: Record<string, never> | null;
            id: string;
            orderId: string;
            /** @description Service level charged for. */
            rateCode?: Record<string, never> | null;
            /** @enum {string} */
            status: "pending" | "dispatched" | "delivered";
            trackingCode?: Record<string, never> | null;
            /** Format: date-time */
            updatedAt: string;
            /** @description What it was rated on, in grams. */
            weightG: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RatesController_rates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateResponseDto"];
                };
            };
        };
    };
    ShipmentsController_deliver: {
        parameters: {
            query?: never;
            header?: {
                /** @description Set by the gateway from the verified JWT. */
                "x-user-id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentResponseDto"];
                };
            };
        };
    };
    ShipmentsController_dispatch: {
        parameters: {
            query?: never;
            header?: {
                /** @description Set by the gateway from the verified JWT. */
                "x-user-id"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispatchShipmentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentResponseDto"];
                };
            };
        };
    };
    ShipmentsController_findByOrder: {
        parameters: {
            query?: never;
            header: {
                "x-user-id": string;
            };
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentResponseDto"];
                };
            };
        };
    };
    RatesController_zones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
