import { MigrationInterface, QueryRunner, Table, TableForeignKey, TableIndex } from 'typeorm';

/**
 * M9: coupons — a discount that has to be asked for, and can run out.
 *
 * The interesting line in this file is `CHK_coupons_within_max_uses`. See below.
 */
export class CreateCouponTables1735003000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'coupons',
        columns: [
          {
            name: 'id',
            type: 'uuid',
            isPrimary: true,
            isGenerated: true,
            generationStrategy: 'uuid',
          },
          // Stored upper-cased; see CouponEntity.code.
          { name: 'code', type: 'varchar', isUnique: true },
          { name: 'discount_id', type: 'uuid' },
          { name: 'max_uses', type: 'integer', isNullable: true },
          { name: 'used_count', type: 'integer', default: 0 },
          { name: 'per_customer_limit', type: 'integer', isNullable: true },
          { name: 'starts_at', type: 'timestamptz', isNullable: true },
          { name: 'ends_at', type: 'timestamptz', isNullable: true },
          { name: 'active', type: 'boolean', default: true },
          { name: 'version', type: 'integer', default: 1 },
          { name: 'created_at', type: 'timestamptz', default: 'now()' },
          { name: 'updated_at', type: 'timestamptz', default: 'now()' },
        ],
        checks: [
          {
            name: 'CHK_coupons_used_count_non_negative',
            expression: '"used_count" >= 0',
          },
          /**
           * **The invariant of this milestone, enforced by the database.**
           *
           * The concurrency control lives in application code — one atomic
           * conditional UPDATE — and application code can be wrong. This makes
           * being wrong *loud*: a race that let an eleventh customer redeem a
           * ten-use coupon fails its transaction here instead of quietly
           * overselling.
           *
           * M8 proved the value of exactly this. Inventory's
           * CHK_stock_reserved_non_negative is the only reason a lost update
           * that had existed since M3 was ever noticed; without it the counter
           * would have drifted silently for another year. A constraint is not a
           * substitute for correct code, it is how you find out the code is not.
           */
          {
            name: 'CHK_coupons_within_max_uses',
            expression: '"max_uses" IS NULL OR "used_count" <= "max_uses"',
          },
          {
            name: 'CHK_coupons_limits_positive',
            expression:
              '("max_uses" IS NULL OR "max_uses" > 0) AND ' +
              '("per_customer_limit" IS NULL OR "per_customer_limit" > 0)',
          },
          // A window that ends before it starts would never apply, and is more
          // likely a typo than an intention. Same check discounts already has.
          {
            name: 'CHK_coupons_window',
            expression: '"starts_at" IS NULL OR "ends_at" IS NULL OR "starts_at" <= "ends_at"',
          },
        ],
      }),
    );

    await queryRunner.createForeignKey(
      'coupons',
      new TableForeignKey({
        name: 'FK_coupons_discount',
        columnNames: ['discount_id'],
        referencedTableName: 'discounts',
        referencedColumnNames: ['id'],
        // RESTRICT, not CASCADE: deleting a discount that a live coupon points
        // at should fail loudly rather than silently disarming the coupon.
        onDelete: 'RESTRICT',
      }),
    );

    await queryRunner.query(
      `CREATE TYPE "redemption_status_enum" AS ENUM ('held', 'committed', 'released')`,
    );

    await queryRunner.createTable(
      new Table({
        name: 'coupon_redemptions',
        columns: [
          {
            name: 'id',
            type: 'uuid',
            isPrimary: true,
            isGenerated: true,
            generationStrategy: 'uuid',
          },
          { name: 'coupon_id', type: 'uuid' },
          // Uniqueness comes from the named UQ_coupon_redemptions_order index
          // below, not from `isUnique` here — setting both creates two indexes
          // enforcing the same rule, and the error then names an autogenerated
          // constraint nobody can find in the codebase.
          { name: 'order_id', type: 'uuid' },
          { name: 'customer_id', type: 'uuid' },
          { name: 'status', type: 'redemption_status_enum', default: `'held'` },
          { name: 'amount_minor', type: 'integer', default: 0 },
          { name: 'created_at', type: 'timestamptz', default: 'now()' },
          { name: 'updated_at', type: 'timestamptz', default: 'now()' },
        ],
        checks: [
          { name: 'CHK_coupon_redemptions_amount_non_negative', expression: '"amount_minor" >= 0' },
        ],
      }),
    );

    await queryRunner.createForeignKey(
      'coupon_redemptions',
      new TableForeignKey({
        name: 'FK_coupon_redemptions_coupon',
        columnNames: ['coupon_id'],
        referencedTableName: 'coupons',
        referencedColumnNames: ['id'],
        onDelete: 'CASCADE',
      }),
    );

    // What makes holding a coupon idempotent: a redelivered order.created
    // violates this index rather than claiming a second use. The same guard
    // inventory gets from its (order_id, product_id) unique index.
    await queryRunner.createIndex(
      'coupon_redemptions',
      new TableIndex({
        name: 'UQ_coupon_redemptions_order',
        columnNames: ['order_id'],
        isUnique: true,
      }),
    );

    // Per-customer limit lookups: "how many has this person already had?"
    await queryRunner.createIndex(
      'coupon_redemptions',
      new TableIndex({
        name: 'IDX_coupon_redemptions_coupon_customer',
        columnNames: ['coupon_id', 'customer_id'],
      }),
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropIndex('coupon_redemptions', 'IDX_coupon_redemptions_coupon_customer');
    await queryRunner.dropIndex('coupon_redemptions', 'UQ_coupon_redemptions_order');
    await queryRunner.dropForeignKey('coupon_redemptions', 'FK_coupon_redemptions_coupon');
    await queryRunner.dropTable('coupon_redemptions');
    await queryRunner.query(`DROP TYPE "redemption_status_enum"`);
    await queryRunner.dropForeignKey('coupons', 'FK_coupons_discount');
    await queryRunner.dropTable('coupons');
  }
}
